import { z } from 'zod';

export const EmployeeSchema = z.object({
  personal_id: z.string("required"),
  org_level_1: z.string("required"),
  org_level_2: z.string().optional(),
  org_level_3: z.string().optional(),
  org_level_4: z.string().optional(),
  org_level_5: z.string().optional(),
  org_level_6: z.string().optional(),
  job_title: z.string("required"),
  status: z.string("required"),
  date_of_appointment: z.string("required"),
  contract_pattern: z.string("required"),
  contract_nature: z.string("required"),
  workplace_governorate: z.string("required"),
  job_category: z.string("required"),
  spouse_name: z.string().optional(),
  spouse_employer: z.string().optional(),
  national_id: z.string("required"),
  full_name: z.string("required"),
  first_name: z.string("required"),
  father_name: z.string("required"),
  surname: z.string("required"),
  mother_name: z.string("required"),
  date_of_birth: z.string("required"),
  place_of_birth: z.string("required"),
  registration: z.string("required"),
  country: z.string("required"),
  original_governorate: z.string("required"),
  region: z.string().optional(),
  residence_governorate: z.string("required"),
  residential_area: z.string("required"),
  marital_status: z.string("required"),
  gender: z.enum(["male", "female"]),
  sham_cash_account: z.string().optional(),
  phone_number: z.string().optional(),
  health_status: z.string("الحالة الصحية مطلوبة"),
  illness_type: z.string().optional(),
  illness_date: z.string().optional(),
  blood_type: z.string().optional(),
  appointment_certificate: z.string().optional(),
  appointment_university: z.string().optional(),
  appointment_college: z.string().optional(),
  appointment_specialization: z.string().optional(),
  appointment_cert_year: z.string().optional(),
  modifying_certificate: z.string().optional(),
  modifying_university: z.string().optional(),
  modifying_college: z.string().optional(),
  modifying_specialization: z.string().optional(),
  modifying_cert_year: z.string().optional(),
  latest_certificate: z.string().optional(),
  current_study_status: z.string().optional(),
  study_stage: z.string().optional(),
  current_study_university: z.string().optional(),
  current_study_college: z.string().optional(),
  current_study_specialization: z.string().optional(),
});

export type EmployeeFormValues = z.infer<typeof EmployeeSchema>;
