// ════════════ LEGAL ════════════
function LegalView() {
  const [sc,sSc]=useState(false);const [toast,sT]=useState(null);const [tick,sTick]=useState(0);
  const up=(id,st)=>{const c=DB.legal.find(x=>x.id===id);if(c)c.status=st;sTick(t=>t+1);sT({message:"تم التحديث",type:"success"});};
  return <div>{toast&&<Ts{...toast}onDone={()=>sT(null)}/>}<div style={{display:"flex",marginBottom:14}}><div style={{flex:1}}/><button onClick={()=>sSc(true)} style={bG}>+ ملف قانوني</button></div><div style={cd}><Tb h={["الرقم","العنوان","الطرف","النوع","المحامي","المحكمة","الجلسة","الحالة",""]}>
    {DB.legal.map(c=><tr key={c.id} style={{borderBottom:`1px solid ${C.border}`}}><Tc mono bold color={C.green}>{c.num}</Tc><Tc>{c.title}</Tc><Tc color={C.muted}>{c.party}</Tc><Tc color={C.muted}>{LTYP.find(t=>t.v===c.case_type)?.l}</Tc><Tc color={C.muted}>{c.lawyer}</Tc><Tc color={C.muted}>{c.court||"—"}</Tc><Tc color={c.next_session&&c.next_session<=dt()?C.danger:C.muted} bold={c.next_session&&c.next_session<=dt()}>{c.next_session||"—"}</Tc><td style={{padding:"10px 9px"}}><Bg map={LS} value={c.status}/></td><Tc><select style={{...inp,width:80,padding:"2px 4px",fontSize:10}} value={c.status} onChange={e=>up(c.id,e.target.value)}>{Object.entries(LS).map(([k,v])=><option key={k} value={k}>{v.l}</option>)}</select></Tc></tr>)}
  </Tb></div><Mo isOpen={sc} onClose={()=>sSc(false)} title="⚖️ ملف قانوني جديد"><FIM investorField withDocs fields={[{k:"title",l:"العنوان *"},{k:"party",l:"الطرف *"},{k:"case_type",l:"النوع",type:"select",opts:LTYP},{k:"lawyer",l:"المحامي"},{k:"court",l:"المحكمة"},{k:"next_session",l:"الجلسة القادمة",type:"date"},{k:"notes",l:"ملاحظات",type:"textarea",span:2}]} init={{title:"",party:"",case_type:"dispute",lawyer:"",court:"",next_session:"",notes:"",inv_id:""}} req={["title","party"]} onSave={fm=>{DB.legal.unshift({...fm,id:DB._n.l++,num:rid("LEG-2025"),inv_id:fm.inv_id?Number(fm.inv_id):null,status:"active"});sSc(false);sTick(t=>t+1);sT({message:"تم الإنشاء",type:"success"});}} onClose={()=>sSc(false)}/></Mo></div>;
}

