// ════════════ PIPELINE ════════════
function PipelineView() {
  const [toast,sT]=useState(null);const [tick,sTick]=useState(0);const [sc,sSc]=useState(false);
  const so=["lead","qualified","proposal","negotiation","won","lost"];
  const upS=(id,s)=>{const p=DB.pipeline.find(x=>x.id===id);if(p){p.stage=s;if(s==="won")p.prob=100;if(s==="lost")p.prob=0;}sTick(t=>t+1);sT({message:"تم التحديث",type:"success"});};
  const act=DB.pipeline.filter(p=>!["won","lost"].includes(p.stage));
  const totV=act.reduce((s,p)=>s+p.value,0);const wV=act.reduce((s,p)=>s+p.value*p.prob/100,0);
  return <div>{toast&&<Ts{...toast}onDone={()=>sT(null)}/>}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(168px,1fr))",gap:10,marginBottom:18}}><SC icon="📈" label="فرص نشطة" value={act.length} color="#7c3aed" gold/><SC icon="💰" label="القيمة الإجمالية" value={fmtSYP(totV)+" ل.س"} color={C.green}/><SC icon="🎯" label="القيمة المرجحة" value={fmtSYP(wV)+" ل.س"} color={C.green}/><SC icon="✅" label="مكسوبة" value={DB.pipeline.filter(p=>p.stage==="won").length} color={C.green}/></div><div style={{display:"flex",marginBottom:14}}><div style={{flex:1}}/><button onClick={()=>sSc(true)} style={bG}>+ فرصة جديدة</button></div><div style={cd}><Tb h={["الفرصة","المستثمر","القيمة","المرحلة","الاحتمال","الإغلاق","تغيير"]}>{DB.pipeline.map(p=>{const inv=DB.investors.find(x=>x.id===p.inv_id);return <tr key={p.id} style={{borderBottom:`1px solid ${C.border}`}}><Tc bold>{p.title}</Tc><Tc color={C.muted}>{inv?.name||"—"}</Tc><Tc bold color={C.success}>{fmtSYP(p.value)} ل.س</Tc><td style={{padding:"10px 9px"}}><Bg map={PS} value={p.stage}/></td><Tc><span style={{fontWeight:700,color:p.prob>=70?C.green:p.prob>=40?C.warning:C.danger}}>{p.prob}%</span></Tc><Tc color={C.muted}>{p.close}</Tc><Tc><select style={{...inp,width:85,padding:"2px 4px",fontSize:10}} value={p.stage} onChange={e=>upS(p.id,e.target.value)}>{so.map(s=><option key={s} value={s}>{PS[s].l}</option>)}</select></Tc></tr>;})}</Tb></div><Mo isOpen={sc} onClose={()=>sSc(false)} title="📈 فرصة استثمارية"><FIM investorField withDocs fields={[{k:"title",l:"العنوان *"},{k:"value",l:"القيمة (ل.س)",type:"number"},{k:"prob",l:"الاحتمال %",type:"number"},{k:"close",l:"الإغلاق المتوقع",type:"date"},{k:"notes",l:"ملاحظات",type:"textarea",span:2}]} init={{title:"",inv_id:"",value:"",prob:"50",close:"",notes:""}} req={["title"]} onSave={fm=>{DB.pipeline.unshift({...fm,id:DB._n.pipe++,inv_id:fm.inv_id?Number(fm.inv_id):null,value:Number(fm.value)||0,prob:Number(fm.prob)||50,stage:"lead",by:1,at:tm()});sSc(false);sTick(t=>t+1);sT({message:"تم الإنشاء",type:"success"});}} onClose={()=>sSc(false)}/></Mo></div>;
}

