// ════════════ PLOTS ════════════
function PlotsView() {
  const [sf,sSf]=useState("");
  let list=[...DB.plots];if(sf)list=list.filter(p=>p.status===sf);
  const zones=[...new Set(DB.plots.map(p=>p.zone))];
  const zs=zones.map(z=>{const zp=DB.plots.filter(p=>p.zone===z);return{z,tot:zp.length,av:zp.filter(p=>p.status==="available").length,al:zp.filter(p=>["allocated","reserved"].includes(p.status)).length,area:zp.reduce((s,p)=>s+p.area,0)};});
  return <div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12,marginBottom:18}}>{zs.map(z=><div key={z.z} style={{...cd,borderTop:`3px solid ${C.green}`}}><h4 style={{fontSize:13,fontWeight:700,margin:"0 0 6px"}}>المنطقة {z.z}</h4><div style={{display:"flex",justifyContent:"space-between",fontSize:11,color:C.muted,marginBottom:5}}><span>{z.tot} قطعة</span><span>{z.area.toLocaleString()} م²</span></div><div style={{height:7,borderRadius:7,background:"#e8f0e8",overflow:"hidden",marginBottom:5}}><div style={{height:"100%",borderRadius:7,background:C.green,width:`${(z.al/z.tot)*100}%`}}/></div><div style={{display:"flex",gap:8,fontSize:10}}><span style={{color:C.green}}>✅ متاح: {z.av}</span><span style={{color:"#3b82f6"}}>🏭 مشغول: {z.al}</span></div></div>)}</div><div style={{display:"flex",gap:8,marginBottom:14}}><select style={{...inp,width:140}} value={sf} onChange={e=>sSf(e.target.value)}><option value="">الكل</option>{Object.entries(PLS).map(([k,v])=><option key={k} value={k}>{v.l}</option>)}</select></div><div style={cd}><Tb h={["القطعة","المنطقة","المساحة","النوع","الإيجار/سنة","البنية التحتية","المستثمر","الحالة"]}>{list.map(p=>{const inv=DB.investors.find(x=>x.id===p.inv_id);return <tr key={p.id} style={{borderBottom:`1px solid ${C.border}`}}><Tc mono bold color={C.green}>{p.num}</Tc><Tc color={C.muted}>{p.zone}</Tc><Tc>{p.area.toLocaleString()} م²</Tc><Tc color={C.muted}>{p.type}</Tc><Tc bold color={C.success}>{fmtSYP(p.rent)} ل.س</Tc><Tc color={C.muted} style={{fontSize:10,maxWidth:170}}>{p.infra}</Tc><Tc>{inv?.name||"—"}</Tc><td style={{padding:"10px 9px"}}><Bg map={PLS} value={p.status}/></td></tr>;})}</Tb></div></div>;
}

