export const DomainErrorCodes = {
  // User validation errors
  NAME_INVALID_LENGTH: 'USER.NAME.INVALID_LENGTH',
  NAME_EMPTY: 'USER.NAME.EMPTY',
  EMAIL_INVALID_FORMAT: 'USER.EMAIL.INVALID_FORMAT',
  EMAIL_DOMAIN_INVALID: 'USER.EMAIL.DOMAIN_INVALID',
  EMAIL_ALREADY_EXISTS: 'USER.EMAIL.ALREADY_EXISTS',
  AGE_NEGATIVE: 'USER.AGE.NEGATIVE',
  
  // User role & permission errors
  INSUFFICIENT_ROLE: 'USER.PERMISSION.INSUFFICIENT_ROLE',
  CANNOT_DEACTIVATE_GENERAL_MANAGER: 'USER.PERMISSION.CANNOT_DEACTIVATE_GENERAL_MANAGER',
  CANNOT_CHANGE_GENERAL_MANAGER_ROLE: 'USER.PERMISSION.CANNOT_CHANGE_GENERAL_MANAGER_ROLE',
  
  // User status errors
  USER_ALREADY_ACTIVE: 'USER.STATUS.ALREADY_ACTIVE',
  USER_ALREADY_INACTIVE: 'USER.STATUS.ALREADY_INACTIVE',
  USER_NOT_FOUND: 'USER.NOT_FOUND',
  
  UNKNOWN_ERROR: 'COMMON.UNKNOWN_ERROR',
} as const;

export type DomainErrorCode = typeof DomainErrorCodes[keyof typeof DomainErrorCodes];